-- Common Ground v26: real Like / Pass / mutual matching
-- Run this once in Supabase SQL Editor before testing v26.

alter table public.profiles
  add column if not exists alcohol_free text,
  add column if not exists deal_goal boolean not null default true,
  add column if not exists deal_smoking boolean not null default false,
  add column if not exists deal_vaping boolean not null default false,
  add column if not exists deal_alcohol boolean not null default false,
  add column if not exists deal_cannabis boolean not null default false;

create table if not exists public.passes (
  id bigint generated by default as identity primary key,
  from_user uuid not null references auth.users(id) on delete cascade,
  to_user uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (from_user, to_user),
  check (from_user <> to_user)
);

alter table public.passes enable row level security;
grant select, insert, delete on public.passes to authenticated;

drop policy if exists "Users can see their own passes" on public.passes;
create policy "Users can see their own passes"
on public.passes for select to authenticated
using ((select auth.uid()) = from_user);

drop policy if exists "Users can create their own passes" on public.passes;
create policy "Users can create their own passes"
on public.passes for insert to authenticated
with check ((select auth.uid()) = from_user);

drop policy if exists "Users can remove their own passes" on public.passes;
create policy "Users can remove their own passes"
on public.passes for delete to authenticated
using ((select auth.uid()) = from_user);

-- Prevent duplicate mutual-match rows regardless of user ordering.
create unique index if not exists matches_unique_pair
on public.matches (least(user_one, user_two), greatest(user_one, user_two));

create or replace function public.like_user(target_user uuid)
returns table(matched boolean, match_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  existing_match_id bigint;
begin
  if me is null then raise exception 'Not signed in'; end if;
  if target_user is null or target_user = me then raise exception 'Invalid target user'; end if;
  if not exists (select 1 from public.profiles where id = target_user) then raise exception 'Profile not found'; end if;

  delete from public.passes where from_user = me and to_user = target_user;
  insert into public.likes(from_user,to_user)
  values(me,target_user)
  on conflict(from_user,to_user) do nothing;

  if exists(select 1 from public.likes where from_user=target_user and to_user=me) then
    insert into public.matches(user_one,user_two)
    values(least(me,target_user),greatest(me,target_user))
    on conflict do nothing;

    select id into existing_match_id
    from public.matches
    where least(user_one,user_two)=least(me,target_user)
      and greatest(user_one,user_two)=greatest(me,target_user)
    limit 1;

    return query select true, existing_match_id;
  else
    return query select false, null::bigint;
  end if;
end;
$$;

grant execute on function public.like_user(uuid) to authenticated;

create or replace function public.pass_user(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
begin
  if me is null then raise exception 'Not signed in'; end if;
  if target_user is null or target_user = me then raise exception 'Invalid target user'; end if;
  delete from public.likes where from_user=me and to_user=target_user;
  insert into public.passes(from_user,to_user)
  values(me,target_user)
  on conflict(from_user,to_user) do nothing;
end;
$$;

grant execute on function public.pass_user(uuid) to authenticated;
